// Public surface of the console's execution and issuance library.
export * from "./execution/types.ts";
export { zatToDecimal, decimalToZat, signedDecimalToZat, ZAT_PER_ZEC, MAX_ZAT } from "./execution/money.ts";
export { checkUnifiedAddress, bech32mCheck, UA_HRP } from "./execution/address.ts";
export { estimateIronwoodFeeZat, MARGINAL_FEE_ZAT } from "./execution/fee.ts";
export { ZkoolAuthError, ZkoolClient, ZkoolGraphqlError, ZkoolTransportError, POOL } from "./execution/zkool-client.ts";
export { checkZkoolToken, mintZkoolToken, readZkoolToken, verifyZkoolToken, ZkoolTokenError, type ZkoolClaims } from "./execution/zkool-token.ts";
export { FileIdempotencyStore, MemoryIdempotencyStore, StoreBusyError, batchDigest } from "./execution/idempotency.ts";
export type { Expect, IdempotencyStore, SubmissionRecord, SubmissionState, TxidEntry } from "./execution/idempotency.ts";
export { ZkoolBackend, isPreBuildRefusal } from "./execution/zkool-backend.ts";
export { batchProblems, MEMO_MAX_BYTES } from "./execution/validate.ts";
export { SqliteIdempotencyStore } from "./execution/sqlite-store.ts";
export { openDb, migrateDb, defaultMigrationsDir, type ConsoleDb, type OpenDbOptions } from "../db/client.ts";
export { autoIssue, IssuanceMismatchError, ReceiptVerificationError } from "./issuance/auto-issue.ts";
export type { AutoIssueResult, IssuedReceipt, ZeceiptCliOptions } from "./issuance/auto-issue.ts";
export { BatchInvalidError, batchNonce, createBatch, getBatch, isSubmitted, listBatches, newBatchId, rateFixed, rateLockFrozen, toExecutionBatch } from "./data/batches.ts";
export type { BatchItemInput, BatchProblem, BatchProblemCode, BatchRecord, BatchSummary, CreateBatchInput } from "./data/batches.ts";
export { Keyring, open as openSealed, seal, SealError, sealedKid } from "./crypto/seal.ts";
export type { WrapKey } from "./crypto/seal.ts";
export { countReceipts, listReceipts, recordReceipts, ReceiptRecordError, rewrapReceipts, sealedKidsInUse } from "./data/receipts.ts";
export { deriveBatchStatus, getBatchStatus } from "./data/status.ts";
export type { BatchFacts, BatchState, BatchStatus, NextAction } from "./data/status.ts";
export type { RecordResult, StoredReceipt } from "./data/receipts.ts";
export { ConfigError, configSummary, keyringFromConfig, loadConfig, loadZkoolToken, scrubSecretEnv } from "./config/env.ts";
export { bootFailureLines, bootServerContext, ContextNotReadyError, SERVER_CONTEXT_KEY, serverContext } from "./server/context.ts";
export type { BootOptions, BootState, ServerContext } from "./server/context.ts";
export { SecretBytes } from "./crypto/secret.ts";
export type { ConfigProblem, ConsoleConfig, CustodyConfig } from "./config/env.ts";
export { compareDecimal, isPositiveDecimal, DECIMAL } from "./rates/decimal.ts";
export { fetchZecUsdQuote, KRAKEN_TICKER_URL, KRAKEN_ZEC_USD_PAIR, MAX_QUOTE_BYTES, RateUnavailableError } from "./rates/kraken.ts";
export type { QuoteOptions, RateFailure, RateQuote } from "./rates/kraken.ts";
export { currentLock, listQuotes, RateRecordError, recordQuote } from "./data/rates.ts";
export { APPROVER, ApprovalError, approvalHmac, approvalMessage, backendId, recordApproval, validApproval } from "./data/approvals.ts";
export type { Approval } from "./data/approvals.ts";
export { listAudit } from "./data/audit.ts";
export type { AuditEvent } from "./data/audit.ts";
export { listRecordLog } from "./data/record-log.ts";
export type { RecordEvent, RecordKind } from "./data/record-log.ts";
export type { QuotePurpose, StoredQuote } from "./data/rates.ts";
export { DEFAULT_MAX_DRIFT_BPS, movedText, pctFromBps, rateDrift } from "./rates/drift.ts";
export type { Drift } from "./rates/drift.ts";
export { createRecipient, getRecipient, KYC_STATUSES, listRecipients, recipientProblems, RecipientInvalidError, SETTLEMENT_PREFS, TAX_FLAGS } from "./data/recipients.ts";
export type { KycStatus, RecipientInput, RecipientProblem, RecipientProblemCode, RecipientRecord, SettlementPref, TaxFlag } from "./data/recipients.ts";
export { createPayable, getPayable, listPayables, PAYABLE_KINDS, payableProblems, PayableInvalidError, ReferenceTakenError, REFERENCE_MAX, SOURCE_URL_MAX, USD_CENTS_MAX } from "./data/payables.ts";
export type { PayableInput, PayableKind, PayableProblem, PayableProblemCode, PayableRecord } from "./data/payables.ts";
export { createBatchFromPayables, MAX_PAYABLES, payableBatchProblems } from "./data/payable-batches.ts";
export { dustZat, usdCentsToZat } from "./rates/convert.ts";
export { voidBatch, VoidError, type VoidErrorCode } from "./data/voids.ts";
export { isPlainText } from "./data/text.ts";
export { csvField, EMPTY, formatUsdCents, formatZec, OPENZCASH_HEADER, openZcashRow, toCsv } from "./export/openzcash.ts";
export type { ExportLine } from "./export/openzcash.ts";
