// Public surface of the console's execution and issuance library.
export * from "./execution/types.ts";
export { zatToDecimal, decimalToZat, signedDecimalToZat, ZAT_PER_ZEC, MAX_ZAT } from "./execution/money.ts";
export { checkUnifiedAddress, bech32mCheck, UA_HRP } from "./execution/address.ts";
export { estimateIronwoodFeeZat, MARGINAL_FEE_ZAT } from "./execution/fee.ts";
export { ZkoolClient, ZkoolGraphqlError, ZkoolTransportError, POOL } from "./execution/zkool-client.ts";
export { FileIdempotencyStore, MemoryIdempotencyStore, StoreBusyError, batchDigest } from "./execution/idempotency.ts";
export type { Expect, IdempotencyStore, SubmissionRecord, SubmissionState, TxidEntry } from "./execution/idempotency.ts";
export { ZkoolBackend, isPreBuildRefusal } from "./execution/zkool-backend.ts";
export { batchProblems, MEMO_MAX_BYTES } from "./execution/validate.ts";
export { SqliteIdempotencyStore } from "./execution/sqlite-store.ts";
export { openDb, migrateDb, defaultMigrationsDir, type ConsoleDb, type OpenDbOptions } from "../db/client.ts";
export { autoIssue, IssuanceMismatchError, ReceiptVerificationError } from "./issuance/auto-issue.ts";
export type { AutoIssueResult, IssuedReceipt, ZeceiptCliOptions } from "./issuance/auto-issue.ts";
export { BatchInvalidError, batchNonce, createBatch, getBatch, listBatches, newBatchId, toExecutionBatch } from "./data/batches.ts";
export type { BatchItemInput, BatchProblem, BatchProblemCode, BatchRecord, BatchSummary, CreateBatchInput } from "./data/batches.ts";
export { Keyring, open as openSealed, seal, SealError, sealedKid } from "./crypto/seal.ts";
export type { WrapKey } from "./crypto/seal.ts";
export { countReceipts, listReceipts, recordReceipts, ReceiptRecordError, rewrapReceipts, sealedKidsInUse } from "./data/receipts.ts";
export { deriveBatchStatus, getBatchStatus } from "./data/status.ts";
export type { BatchFacts, BatchState, BatchStatus, NextAction } from "./data/status.ts";
export type { RecordResult, StoredReceipt } from "./data/receipts.ts";
export { ConfigError, configSummary, keyringFromConfig, loadConfig, scrubSecretEnv } from "./config/env.ts";
export { bootFailureLines, bootServerContext, ContextNotReadyError, SERVER_CONTEXT_KEY, serverContext } from "./server/context.ts";
export type { BootOptions, BootState, ServerContext } from "./server/context.ts";
export { SecretBytes } from "./crypto/secret.ts";
export type { ConfigProblem, ConsoleConfig, CustodyConfig } from "./config/env.ts";
export { compareDecimal, isPositiveDecimal, DECIMAL } from "./rates/decimal.ts";
export { fetchZecUsdQuote, KRAKEN_TICKER_URL, KRAKEN_ZEC_USD_PAIR, MAX_QUOTE_BYTES, RateUnavailableError } from "./rates/kraken.ts";
export type { QuoteOptions, RateFailure, RateQuote } from "./rates/kraken.ts";
