CREATE TABLE `rate_quotes` (
	`org_id` text NOT NULL,
	`batch_id` text NOT NULL,
	`seq` integer NOT NULL,
	`purpose` text NOT NULL,
	`source` text NOT NULL,
	`pair` text NOT NULL,
	`bid` text NOT NULL,
	`ask` text NOT NULL,
	`last` text NOT NULL,
	`rate` text NOT NULL,
	`fetched_at` text NOT NULL,
	`recorded_at` text NOT NULL,
	PRIMARY KEY(`org_id`, `batch_id`, `seq`),
	FOREIGN KEY (`org_id`,`batch_id`) REFERENCES `batches`(`org_id`,`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "rate_quotes_seq" CHECK(typeof("rate_quotes"."seq") = 'integer' and "rate_quotes"."seq" >= 1),
	CONSTRAINT "rate_quotes_purpose" CHECK("rate_quotes"."purpose" in ('lock', 'execution')),
	CONSTRAINT "rate_quotes_source" CHECK("rate_quotes"."source" in ('kraken')),
	CONSTRAINT "rate_quotes_pair" CHECK(length("rate_quotes"."pair") between 1 and 32),
	CONSTRAINT "rate_quotes_bid" CHECK(typeof("rate_quotes"."bid") = 'text' and length("rate_quotes"."bid") between 1 and 34 and "rate_quotes"."bid" glob '[0-9]*' and "rate_quotes"."bid" not glob '*[^0-9.]*' and "rate_quotes"."bid" not glob '*.*.*' and "rate_quotes"."bid" not glob '*.'),
	CONSTRAINT "rate_quotes_ask" CHECK(typeof("rate_quotes"."ask") = 'text' and length("rate_quotes"."ask") between 1 and 34 and "rate_quotes"."ask" glob '[0-9]*' and "rate_quotes"."ask" not glob '*[^0-9.]*' and "rate_quotes"."ask" not glob '*.*.*' and "rate_quotes"."ask" not glob '*.'),
	CONSTRAINT "rate_quotes_last" CHECK(typeof("rate_quotes"."last") = 'text' and length("rate_quotes"."last") between 1 and 34 and "rate_quotes"."last" glob '[0-9]*' and "rate_quotes"."last" not glob '*[^0-9.]*' and "rate_quotes"."last" not glob '*.*.*' and "rate_quotes"."last" not glob '*.'),
	CONSTRAINT "rate_quotes_rate_is_bid" CHECK("rate_quotes"."rate" = "rate_quotes"."bid"),
	CONSTRAINT "rate_quotes_fetched_at" CHECK(typeof("rate_quotes"."fetched_at") = 'text' and length("rate_quotes"."fetched_at") = 24 and "rate_quotes"."fetched_at" glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
	CONSTRAINT "rate_quotes_recorded_at" CHECK(typeof("rate_quotes"."recorded_at") = 'text' and length("rate_quotes"."recorded_at") = 24 and "rate_quotes"."recorded_at" glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
);
