-- Custom migration (slice I4b, review round 1): an address change inside the kept prefix was logged as a change naming
-- no field. The WHEN clause compared the full addresses, but the detail recorded only the abridged forms, and two
-- addresses sharing the prefix abridge to the same text. Now the address entry decides on the full addresses: the
-- abridged forms when they differ (as the pages show them), and the full previous and current addresses, marked
-- "full", when they abridge alike, so a change is never recorded without its field. Addresses are not secret: the
-- recipients table holds them in full. 0022 is released, so the trigger is replaced here rather than edited there.
DROP TRIGGER `record_recipients_update`;
--> statement-breakpoint
CREATE TRIGGER `record_recipients_update` AFTER UPDATE ON `recipients`
WHEN OLD.`display_name` IS NOT NEW.`display_name` OR OLD.`address` IS NOT NEW.`address` OR OLD.`network` IS NOT NEW.`network` OR OLD.`kyc_status` IS NOT NEW.`kyc_status` OR OLD.`tax_flag` IS NOT NEW.`tax_flag` OR OLD.`settlement_pref` IS NOT NEW.`settlement_pref` OR OLD.`notes` IS NOT NEW.`notes`
BEGIN INSERT INTO `record_log` (`org_id`, `kind`, `record_id`, `at`, `action`, `detail`) VALUES (NEW.`org_id`, 'recipient', NEW.`id`, NEW.`updated_at`, 'changed', json_object('fields', json_object('displayName', CASE WHEN OLD.`display_name` IS NOT NEW.`display_name` THEN json_object('previous', OLD.`display_name`, 'current', NEW.`display_name`) END, 'address', CASE WHEN OLD.`address` IS NOT NEW.`address` THEN (CASE WHEN (CASE WHEN length(OLD.`address`) <= instr(OLD.`address`, '1') + 26 THEN OLD.`address` ELSE substr(OLD.`address`, 1, instr(OLD.`address`, '1') + 25) || '…' END) IS NOT (CASE WHEN length(NEW.`address`) <= instr(NEW.`address`, '1') + 26 THEN NEW.`address` ELSE substr(NEW.`address`, 1, instr(NEW.`address`, '1') + 25) || '…' END) THEN json_object('previous', CASE WHEN length(OLD.`address`) <= instr(OLD.`address`, '1') + 26 THEN OLD.`address` ELSE substr(OLD.`address`, 1, instr(OLD.`address`, '1') + 25) || '…' END, 'current', CASE WHEN length(NEW.`address`) <= instr(NEW.`address`, '1') + 26 THEN NEW.`address` ELSE substr(NEW.`address`, 1, instr(NEW.`address`, '1') + 25) || '…' END) ELSE json_object('previous', OLD.`address`, 'current', NEW.`address`, 'full', json('true')) END) END, 'network', CASE WHEN OLD.`network` IS NOT NEW.`network` THEN json_object('previous', OLD.`network`, 'current', NEW.`network`) END, 'kycStatus', CASE WHEN OLD.`kyc_status` IS NOT NEW.`kyc_status` THEN json_object('previous', OLD.`kyc_status`, 'current', NEW.`kyc_status`) END, 'taxFlag', CASE WHEN OLD.`tax_flag` IS NOT NEW.`tax_flag` THEN json_object('previous', OLD.`tax_flag`, 'current', NEW.`tax_flag`) END, 'settlementPref', CASE WHEN OLD.`settlement_pref` IS NOT NEW.`settlement_pref` THEN json_object('previous', OLD.`settlement_pref`, 'current', NEW.`settlement_pref`) END, 'notes', CASE WHEN OLD.`notes` IS NOT NEW.`notes` THEN json_object('previous', OLD.`notes`, 'current', NEW.`notes`) END))); END;
